### ISSUE TITLE
Error: Invalid manifest name

### ISSUE THREAD

**Issue by tombomb** [VTTAssets/vtta-party#7]
after updating to 5.5 trying to do an update on old install mods throws 
```
Error: Invalid manifest name https://update.vttassets.com/modules/vtta-party/latest for package type module
```
this is for all VTTA mods

**Comment by apoapostolov** [comment]
Remove them and re-add them from the new Module Browser.

**Comment by VTTAssets** [comment]
I changed something on my backend, should be good for now
